### ISSUE TITLE
Consider mandatory/optional params and include in Swagger

### ISSUE THREAD

**Issue by ratcashdev** [sdaschner/jaxrs-analyzer#20]
The definition
```
@GET
	@Path("{resourceId}/list")
	@Produces({MediaType.APPLICATION_JSON + ";charset=UTF-8", MediaType.APPLICATION_XML + ";charset=UTF-8"})
	public void list(@PathParam("resourceId") final Long resourceId, @QueryParam("orderIds") String orderIds,
			@Context final HttpHeaders headers, @Suspended AsyncResponse response) {
```
results in the following JSON:
```
"/restricted/shops/{resourceId}/list": {
			"get": {
				"consumes": [],
				"produces": ["application/json;charset=UTF-8", "application/xml;charset=UTF-8"],
				"parameters": [{
						"name": "resourceId",
						"in": "path",
						"required": true,
						"type": "integer"
					}, {
						"name": "orderIds",
						"in": "query",
						"required": true,
						"type": "string"
					}, {
						"name": "body",
						"in": "body",
						"required": true,
						"schema": {}
					}],
```
here, a couple of incorrect values:
* BODY should not be required. Not sure, how to tell this to the analyzer.
* orderIds are optional (there's no `@NotNull` annotation)
* the PRODUCES should (imho) ignore the charset.

**Comment by sdaschner** [comment]
You're right. The Analyzer currently doesn't "know" Async Responses yet (see #6), this is why it wrongly consideres this parameter as the body.

The information about mandatory or optional parameters is just not taken yet; I always set the Swagger `required` to `true`...

IMO the consumes / produces media types should contain the full type (including parameters, see https://tools.ietf.org/html/rfc7231#section-3.1.1.1), as the parameter might as well be used in order to version several entities of the API (e.g. application/json;v=1). This information then could be relevant to the user. I would fully agree for charset definitions, but these parameters aren't solely restricted to that.

I'll change the title of your issue to the required parameters as the first issue is tracked in #6.

Thanks for issuing that! :-)

**Comment by ratcashdev** [comment]
Do you think it would be an acceptable 'exception' to replace ';charset=[a-z0-9]*' with an empty string? Though i can imagine someone would want to keep this. Then again, it is always possible to post-process the generated file.

**Comment by sdaschner** [comment]
Yes, I also can imagine someone wants to keep this information as it seems that there was a valid reason to explicitly add it in the first place.

**Comment by sdaschner** [comment]
Duplicate to #55.
