### ISSUE TITLE
Supply resource method name as operationId

### ISSUE THREAD

**Issue by darylteo** [sdaschner/jaxrs-analyzer#63]
Again, for Swagger - if you don't supply the operationId in the spec, swagger-codegen generates some hideous looking method names based on the full resource path like `.resourcePath1Path2Param1Param2Get()`.

Granted, this forces developers to use strict naming conventions for their resource methods, such as `getOneResource()` and `getManyResource()`. But I suspect this would be a better proposition anyway - the resourceMethods will match 1-1 with the generated API interface.

**Comment by sdaschner** [comment]
Sorry for the late response on this whole topic -- especially bc/ you already invested time in a PR.

Well, TBH I still don't see the big benefit from Swagger's operationId -- or at least not why we should explicitely take the JAX-RS resource method's name here. The problem is that following the Swagger spec this name has to be unique thoughout the whole API, so just taking the method name won't be enough, we would also have to check that the names are unique and if not, add some extra information, like the classname, and vice versa, if that is not enough than add the Java package name as well...

And frankly I don't see the value from having a matching operationId... WDYT?

**Comment by darylteo** [comment]
@sdaschner because swagger-codegen's JS method names are horrible! That's why =)

**Comment by sdaschner** [comment]
Haha, yeah I guess that's true.

The problem is that we can't guarantee better names in any cases -- only if the developer makes sure the method names are unique and we need to gather and transport more data which doesn't add too much value (in terms of the documented data). Do you see my point?

And surely we would need some extra logic to guarantee the uniqueness. But TBH I would rather focus for the improvements which add some more documented value or fix potential issues chaning to ASM has introduced, e.g. adding support for `@Suspended` methods or supporting JavaDocs, you agree?

**Comment by darylteo** [comment]
Do you know of any annotations we can use as a alternative? 

I'm happy to keep it in my local changes for now. As far as priorities go, my priorities are whatever aids me in getting this job done. I'm aware this won't necessarily coincide with your priorities so I'm happy for you to push back on it while I battle other stuff.

**Comment by sdaschner** [comment]
No, actually that was always the goal of my tool to use plain JAX-RS -- or rather plain EE specs only wo/ any other things you don't want to add to your project, like the Swagger annotations. These are the only annotations that come to my mind for that operationId.

Ok, glad you can understand that :)

Yes, JavaDoc might be a nice "hack" to add extra stuff like that -- which is optional then but doesn't need any extra dependencies but just, for example, JavaDoc tags defined by us.

**Comment by sdaschner** [comment]
Kindly rejecting #64 as discussed. Feel free to hold it in a separate branch, etc.
